### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by kratos-te**
this is what you asked for the first

### CODE REVIEW

**Comment by alexmazaltov** [comment]
Thank you @kratos-te we just finished the conversation and you made the fix that i was not able to do it by myself.
Can you explain me how you manged to find a solution?

**Comment by kratos-te** [comment]
first check the node version on your computer.
after checking all packages are installed correctly, I checked the path setting in tsconfig.json.

**Comment by alexmazaltov** [comment]
@kratos-te Unfortunatelly i can't run it succesfully. I tried with `yarn` and then removed the node_modules i tried with `npm`. 

## You say to check node version? - `how to know which version to use`

And how to check if `all packages are installed correctly`

Want to make sure that it will be rendered with my changes that supposed to significantly improve the UI of my homepage using `shadcn/ui` and `tailwind`

зображення

**Comment by kratos-te** [comment]
"node --version" to check node version
and you have to run `npm install -D "tailwindcss-animate"`

**Review by ionescu77 — APPROVED** [review]
Good work.
Very nice implementation of environment variables (and different setting-files for dev, staging, production).
Did not know about this:
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables

API Key is safe
Nice touch

**Comment by Agent009** [comment]
Thanks for your input guys, Since there is company specific info in the PR, I'll have to reject it, but I'll incorporate some of the improvements. Thanks again for your valuable time and input.

**Pull request closed without merging**
